### ISSUE TITLE
Preprocessing run until 100% but only produce 0KB open4_train.pkl.

### ISSUE THREAD

**Issue by romasigo** [youngbin-ro/Multi2OIE#1]
Hallo. I followed the step, unfortunately in preprocessing stage can not generate the open4_train.pkl as expected.
`cd utils
python preprocess.py \
    --mode 'train' \
    --data '../datasets/structured_data.json' \
    --save_path '../datasets/openie4_train.pkl' \
    --bert_config 'bert-base-cased' \
    --max_len 64`

I suspect  there is a problem with the jsonschema package that affected this issue. There is a version incompatibility there. At the Environmental Setup stage using pip install -r requirements.txt, an error appears like this:
`ERROR: nbclient 0.5.3 has requirement jupyter-client> = 6.1.5, but you'll have jupyter-client 5.3.5 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium == 0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug <0.2.7,> = 0.2.5, but you'll have imgaug 0.2.9 which is incompatible.`

But I'm not sure what causes this issue, yet.

**Comment by youngbin-ro** [comment]
I apologize for the late reply.
For me, the code `pip install -r requirements.txt` works fine.
It is recommended to run the installation code after running `pip install --upgrade pip`.
Otherwise, please check whether other unspecified libraries are installed in your environment.

Additionally, for ease of use, I have released the `openie4_train.pkl` file, so please check it.
https://drive.google.com/file/d/1DrWj1CjLFIno-UBfLI3_uIratN4QY6Y3/view?usp=sharing
